services:
  backends:
    image: "gestionetudiant"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gestionNote
      - SPRING_DATASOURCE_USERNAME=bony
      - SPRING_DATASOURCE_PASSWORD=33rthk
    ports:
      - "8000:8080"
    depends_on:
      - postgres
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=gestionNote
      - POSTGRES_USER=bony
      - POSTGRES_PASSWORD=33rthk
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
